In [3]:
import numpy as np

In [49]:
# 16.1
s = [1,3,0,5,3,5,6,8,8,2,12]
f = [4,5,6,7,9,9,10,11,12,14,16]

In [13]:
# 16.1
def RecursiveActivitySelection(s, f, k, n):
    m = k+1
    while m<=n and s[m]<f[k]:
        m += 1
    if m<=n:
        print(s[m],f[m])
        return [m,] + RecursiveActivitySelection(s, f, m, n)
    else:
        return []

In [14]:
s_fictitious = [0]+s
f_fictitious = [0]+f
RecursiveActivitySelection(s_fictitious,f_fictitious,0,11)

1 4
5 7
8 11
12 16


[1, 4, 8, 11]

In [15]:
def GreedyActivitySelection(s,f):
    k = 1
    A = [1,]
    for m in range(2,len(s)):
        if s[m]>=f[k]:
            A = A + [m,]
            k = m
    return A

In [16]:
GreedyActivitySelection(s_fictitious, f_fictitious)

[1, 4, 8, 11]

In [59]:
s = [1,3,0,5,3,5,6,8,8,2,12]
f = [4,5,6,7,9,9,10,11,12,14,16]

#16.1.1
def DynamicActivitySelelction(s,f):
    n = len(s)
    dp_mat = np.zeros((n,n), dtype='int')
    
    retrieve_mat = np.empty((n,n), dtype='int')
    retrieve_mat.fill(-1)
    for l in range(2,n+1):
        for i in range(0, n-l):
            j = i+l # open
            for k in range(i,j):
                if s[k]>=f[i] and f[k]<=s[j]:
                    cur_val = dp_mat[i,k]+dp_mat[k,j]+1
                    if dp_mat[i,j]<cur_val:
                        dp_mat[i,j] = cur_val
                        retrieve_mat[i,j] = k
    return dp_mat, retrieve_mat

In [60]:
DynamicActivitySelelction(s,f)

(array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 array([[-1, -1, -1, -1, -1, -1, -1,  3,  3, -1,  3],
        [-1, -1, -1, -1, -1, -1, -1,  3,  3, -1,  3],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  6],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  7],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1

In [9]:
#16.2.1
def KnapsackDP(W, w, v):
    n = len(w)
    dp = np.zeros((n+1,W+1))
    for i in range(1,n+1):
        for j in range(1,W+1):
            if j>w[i-1]:
                dp[i,j] = max(dp[i-1,j], dp[i-1,j-w[i-1]]+v[i-1])
            else:
                dp[i,j] = dp[i-1,j]
    return dp

In [10]:
W = 50
w = [10,20,30]
v = [60,100,120]
KnapsackDP(W,w,v)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 160., 160.,
        160., 160., 160., 160., 160., 160., 160., 160., 160., 160., 160.,
        16

## 16.3 Huffman codes

In [96]:
from functools import total_ordering

@total_ordering
class Node:
    def __init__(self, freq, character):
        self.character = character
        self.freq = freq
        self.left = None
        self.right = None
    def __eq__(self, other):
        return self.freq == other.freq
    def __lt__(self, other):
        return self.freq < other.freq
    def __repr__(self):
        return str(self.freq)+' '+self.character

In [108]:
import heapq
import copy
def HUFFMAN(C):
    n = len(C)
    Q = copy.deepcopy(C) # not change C
    print(Q)
    heapq.heapify(Q)
    print(Q)
    for i in range(n-1):
        z = Node(-1, None)
        z.left = x =heapq.heappop(Q)
        z.right = y = heapq.heappop(Q)
        z.freq = x.freq + y.freq
        heapq.heappush(Q, z)
    return heapq.heappop(Q) # return the root of the tree

In [109]:
C = []
C.append(Node(45, 'a'))
C.append(Node(13, 'b'))
C.append(Node(12, 'c'))
C.append(Node(16, 'd'))
C.append(Node(9, 'e'))
C.append(Node(5, 'f'))

In [110]:
root = HUFFMAN(C)

[45 a, 13 b, 12 c, 16 d, 9 e, 5 f]
[5 f, 9 e, 12 c, 16 d, 13 b, 45 a]


In [111]:
root.freq, root.left.freq, root.right.freq

(100, 45, 55)

In [112]:
l = []
l.append(root)
while len(l)>0:
    level = len(l)
    print(level)
    for i in range(level):
        cur = l.pop(0)
        print((cur.freq, cur.character), end='#')
        if cur.right:
            l.append(cur.right)
        if cur.left:
            l.append(cur.left)
    print()

1
(100, None)#
2
(55, None)#(45, 'a')#
2
(30, None)#(25, None)#
4
(16, 'd')#(14, None)#(13, 'b')#(12, 'c')#
2
(9, 'e')#(5, 'f')#
