In [1]:
import numpy as np
import sys

# 15.2 Matrix-chain multiplication

In [41]:
def matrix_chain_order(p):
    n = len(p)-1
    m = np.zeros((n,n), dtype='int')
    s = np.zeros((n,n), dtype='int')
    for l in range(2, n+1):
        for i in range(0, n-l+1):
            j = i+l-1
            m[i,j] = sys.maxsize
#             print(i, j)
            for k in range(i,j):
                q = m[i,k]+m[k+1,j]+p[i]*p[k+1]*p[j+1]
                if q<m[i,j]:
                    m[i,j]=q
                    s[i,j]=k+1
    return m, s

In [42]:
p = [30, 35, 15,5,10,20,25] # 7 items
m, s = matrix_chain_order(p)

In [43]:
m

array([[    0, 15750,  7875,  9375, 11875, 15125],
       [    0,     0,  2625,  4375,  7125, 10500],
       [    0,     0,     0,   750,  2500,  5375],
       [    0,     0,     0,     0,  1000,  3500],
       [    0,     0,     0,     0,     0,  5000],
       [    0,     0,     0,     0,     0,     0]])

In [44]:
s

array([[0, 1, 1, 3, 3, 3],
       [0, 0, 2, 3, 3, 3],
       [0, 0, 0, 3, 3, 3],
       [0, 0, 0, 0, 4, 5],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])

In [49]:
def print_optimal_parens(s,i,j):
    if i==j:
        print(f'A{i+1}', end='')
    else:
        print('(', end='')
        print_optimal_parens(s, i, s[i,j]-1)
        print_optimal_parens(s, s[i,j], j)
        print(')', end='')
        

In [50]:
print_optimal_parens(s, 0, 5)

((A1(A2A3))((A4A5)A6))

# 15.4 Longest common subsequence

In [18]:
def LCS_length(X, Y):
    m = len(X)
    n = len(Y)
    B = np.empty((m+1, n+1), dtype='int')
    C = np.empty((m+1, n+1), dtype='int')
    for i in range(m+1):
        C[i,0] = 0
        B[i,0] = -1
    for j in range(n+1):
        C[0,j] = 0
        B[0,j] = -1
    # up left concer arrow 0, up arrow 1, left arrow 2
    for i in range(1, m+1):
        for j in range(1, n+1):
            if X[i-1]==Y[j-1]:
                C[i,j] = C[i-1,j-1]+1
                B[i,j] = 0
            elif C[i-1,j] >= C[i,j-1]:
                C[i,j] = C[i-1, j]
                B[i,j] = 1
            else:
                C[i,j] = C[i, j-1]
                B[i,j] = 2
    return C, B

In [19]:
X = ['A','B','C','B','D','A','B']
Y = ['B','D','C','A','B','A']

In [20]:
C, B = LCS_length(X, Y)

In [21]:
C

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1, 2, 2],
       [0, 1, 1, 2, 2, 2, 2],
       [0, 1, 1, 2, 2, 3, 3],
       [0, 1, 2, 2, 2, 3, 3],
       [0, 1, 2, 2, 3, 3, 4],
       [0, 1, 2, 2, 3, 4, 4]])

In [22]:
B

array([[-1, -1, -1, -1, -1, -1, -1],
       [-1,  1,  1,  1,  0,  2,  0],
       [-1,  0,  2,  2,  1,  0,  2],
       [-1,  1,  1,  0,  2,  1,  1],
       [-1,  0,  1,  1,  1,  0,  2],
       [-1,  1,  0,  1,  1,  1,  1],
       [-1,  1,  1,  1,  0,  1,  0],
       [-1,  0,  1,  1,  1,  0,  1]])

In [23]:
def PRINT_LCS(B, X, i,j):
    if i==0 or j==0:
        return
    if B[i,j]==0:
        PRINT_LCS(B,X,i-1,j-1)
        print(X[i-1], end='')
    elif B[i,j]==1:
        PRINT_LCS(B,X,i-1,j)
    else:
        PRINT_LCS(B,X,i,j-1)

In [24]:
PRINT_LCS(B, X, len(X), len(Y))

BCBA

# Exercises 15.4-1

In [25]:
X = ['1','0','0','1','0','1','0','1']
Y = ['0','1','0','1','1','0','1','1','0']

In [35]:
C, B = LCS_length(X, Y)
C[8, 9]

6

In [36]:
PRINT_LCS(B,X,8,9)

100110

In [45]:
def PRINT_LCS2(C, X, i, j):
    if i==0 or j ==0:
        return
    if C[i,j]==C[i-1,j]+1 and C[i,j-1]+1:
        PRINT_LCS2(C, X, i-1, j-1)
        print(X[i-1], end='')
    elif C[i,j]==C[i-1,j]:
        PRINT_LCS2(C, X, i-1, j)
    else:
        PRINT_LCS2(C, X, i, j-1)

In [46]:
PRINT_LCS2(C,X,8,9)

100110

In [39]:
C

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 2, 2, 2, 2, 2, 2, 2],
       [0, 1, 1, 2, 2, 2, 3, 3, 3, 3],
       [0, 1, 2, 2, 3, 3, 3, 4, 4, 4],
       [0, 1, 2, 3, 3, 3, 4, 4, 4, 5],
       [0, 1, 2, 3, 4, 4, 4, 5, 5, 5],
       [0, 1, 2, 3, 4, 4, 5, 5, 5, 6],
       [0, 1, 2, 3, 4, 5, 5, 6, 6, 6]])

In [40]:
B

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1,  1,  0,  2,  0,  0,  2,  0,  0,  2],
       [-1,  0,  1,  0,  2,  2,  0,  2,  2,  0],
       [-1,  0,  1,  0,  1,  1,  0,  2,  2,  0],
       [-1,  1,  0,  1,  0,  0,  1,  0,  0,  2],
       [-1,  0,  1,  0,  1,  1,  0,  1,  1,  0],
       [-1,  1,  0,  1,  0,  0,  1,  0,  0,  1],
       [-1,  0,  1,  0,  1,  1,  0,  1,  1,  0],
       [-1,  1,  0,  1,  0,  0,  1,  0,  0,  1]])

# Exercises 15.4-5

In [ ]:
# Example 2, 5, 1, 4, 3, 9, 6, 7
# Solution: 1. sort list 2. find longest common subsequence
A = []