In [3]:
import numpy as np

In [49]:
# 16.1
s = [1,3,0,5,3,5,6,8,8,2,12]
f = [4,5,6,7,9,9,10,11,12,14,16]

In [13]:
# 16.1
def RecursiveActivitySelection(s, f, k, n):
    m = k+1
    while m<=n and s[m]<f[k]:
        m += 1
    if m<=n:
        print(s[m],f[m])
        return [m,] + RecursiveActivitySelection(s, f, m, n)
    else:
        return []

In [14]:
s_fictitious = [0]+s
f_fictitious = [0]+f
RecursiveActivitySelection(s_fictitious,f_fictitious,0,11)

1 4
5 7
8 11
12 16


[1, 4, 8, 11]

In [15]:
def GreedyActivitySelection(s,f):
    k = 1
    A = [1,]
    for m in range(2,len(s)):
        if s[m]>=f[k]:
            A = A + [m,]
            k = m
    return A

In [16]:
GreedyActivitySelection(s_fictitious, f_fictitious)

[1, 4, 8, 11]

In [59]:
s = [1,3,0,5,3,5,6,8,8,2,12]
f = [4,5,6,7,9,9,10,11,12,14,16]

#16.1.1
def DynamicActivitySelelction(s,f):
    n = len(s)
    dp_mat = np.zeros((n,n), dtype='int')
    
    retrieve_mat = np.empty((n,n), dtype='int')
    retrieve_mat.fill(-1)
    for l in range(2,n+1):
        for i in range(0, n-l):
            j = i+l # open
            for k in range(i,j):
                if s[k]>=f[i] and f[k]<=s[j]:
                    cur_val = dp_mat[i,k]+dp_mat[k,j]+1
                    if dp_mat[i,j]<cur_val:
                        dp_mat[i,j] = cur_val
                        retrieve_mat[i,j] = k
    return dp_mat, retrieve_mat

In [60]:
DynamicActivitySelelction(s,f)

(array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 array([[-1, -1, -1, -1, -1, -1, -1,  3,  3, -1,  3],
        [-1, -1, -1, -1, -1, -1, -1,  3,  3, -1,  3],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  6],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  7],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1

In [1]:
#16.2.1
def KnapsackDP(W, w, v):
    n = len(w)
    dp = np.zeros((n+1,W))
    for i in range(n):
        for j in range(W):
            if j>w[i]:
                dp[i+1,j] = max(dp[i,j], dp[i,j-w[i]]+v[i])
            else:
                dp[i+1,j] = dp[i,j]
    return dp

In [4]:
W = 50
w = [10,20,30]
v = [60,100,120]
KnapsackDP(W,w,v)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,
         60.,  60.,  60.,  60.,  60.,  60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60.,  60., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 160., 160.,
        160., 160., 160., 160., 160., 160., 160., 160., 160., 160., 160.,
        160., 160., 16